<a href="https://colab.research.google.com/github/holdenkim/codingT/blob/main/BBGS_part4_456.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#4.인공신경망

In [4]:
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd
data = pd.read_csv('breast-cancer-wisconsin.csv')
X = data[data.columns[1:10]]
y = data['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(X_train)
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [5]:
from sklearn.neural_network import MLPClassifier

In [6]:
mlp = MLPClassifier()
mlp.fit(X_scaled_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [7]:
pred_train = mlp.predict(X_scaled_train)
pred_test = mlp.predict(X_scaled_test)

In [8]:
print (mlp.score(X_scaled_train, y_train))
print (mlp.score(X_scaled_test, y_test))

0.9765625
0.9473684210526315


In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)

In [11]:
print(cm_train)
print(cm_test)

[[334   7]
 [  5 166]]
[[102   1]
 [  8  60]]


In [12]:
from sklearn.metrics import classification_report

In [13]:
cr_train = classification_report(y_train, pred_train)
cr_test = classification_report(y_test, pred_test)

In [14]:
print(cr_train)
print(cr_test)

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       341
           1       0.96      0.97      0.97       171

    accuracy                           0.98       512
   macro avg       0.97      0.98      0.97       512
weighted avg       0.98      0.98      0.98       512

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       103
           1       0.98      0.88      0.93        68

    accuracy                           0.95       171
   macro avg       0.96      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [15]:
param_grid = {
     "hidden_layer_sizes":[10,30,50,100],
    "solver":['sgd','adam'],
    "activation":['tanh','relu']
}

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
gs = GridSearchCV(MLPClassifier(), param_grid, cv=5)

In [18]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=200, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state=None, shuffle=True,
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid=

In [19]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'activation': 'tanh', 'hidden_layer_sizes': 50, 'solver': 'adam'}
0.972663240053303
0.9473684210526315


In [20]:
from scipy.stats import randint
param_distribs = {
    'hidden_layer_sizes': randint(low=10, high=100),
    'solver':['sgd','adam'],
    'activation':['tanh','relu']
}

In [21]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(MLPClassifier(), param_distribs, cv=5)

In [22]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                           batch_size='auto', beta_1=0.9,
                                           beta_2=0.999, early_stopping=False,
                                           epsilon=1e-08,
                                           hidden_layer_sizes=(100,),
                                           learning_rate='constant',
                                           learning_rate_init=0.001,
                                           max_fun=15000, max_iter=200,
                                           momentum=0.9, n_iter_no_change=10,
                                           nesterovs_momentum=True, power_t=0.5,
                                           random...
                                           validation_fraction=0.1,
                                           verbose=False, warm_start=False),
                   iid='deprecated

In [23]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'activation': 'tanh', 'hidden_layer_sizes': 59, 'solver': 'adam'}
0.972663240053303
0.9473684210526315


In [24]:
data = pd.read_csv('house_price.csv')
X = data[data.columns[0:4]]
y = data["house_value"]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
mms = MinMaxScaler()
mms.fit(X_train)
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [25]:
from sklearn.neural_network import MLPRegressor

In [26]:
mlp = MLPRegressor()

In [27]:
mlp.fit(X_scaled_train, y_train)
pred_train = mlp.predict(X_scaled_train)
pred_test = mlp.predict(X_scaled_test)
print(mlp.score(X_scaled_train, y_train))
print(mlp.score(X_scaled_test, y_test))

-2.950434351770636
-2.908433946209729


In [28]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [29]:
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)
print(np.sqrt(MSE_train))
print(np.sqrt(MSE_test))

189702.6809237871
189000.89564072806


In [30]:
mlp = MLPRegressor(hidden_layer_sizes=(64,64,64), activation='relu', random_state=1, max_iter=2000)

In [31]:
mlp.fit(X_scaled_train, y_train)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(64, 64, 64), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=2000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=1, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [32]:
pred_train = mlp.predict(X_scaled_train)
pred_test = mlp.predict(X_scaled_test)
print(mlp.score(X_scaled_train, y_train))
print(mlp.score(X_scaled_test, y_test))

0.5935001592636364
0.6061518108236675


In [33]:
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)
print(np.sqrt(MSE_train))
print(np.sqrt(MSE_test))

60852.89356437536
59996.6360215003


In [34]:
#다층 퍼셉트론은 하이퍼파라메터가 매우 많고 모델에 대한 깊은 이해가 있어야 한다.기본 설정으로는 좋은 결과를 얻기 힘듬

#5. 서포트벡터머신

In [35]:
import pandas as pd
data = pd.read_csv('breast-cancer-wisconsin.csv')
X = data[data.columns[1:10]]
y = data['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(X_train)
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [36]:
from sklearn.svm import SVC
model=SVC()
model.fit(X_scaled_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)
print(model.score(X_scaled_train, y_train))
print(model.score(X_scaled_test, y_test))

0.978515625
0.9473684210526315


In [38]:
from sklearn.metrics import confusion_matrix
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)
print(cm_test)

from sklearn.metrics import classification_report
cr_train = classification_report(y_train, pred_train)
cr_test = classification_report(y_test, pred_test)
print(cr_test)

[[101   2]
 [  7  61]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       103
           1       0.97      0.90      0.93        68

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [39]:
param_grid = [{'kernel':['rbf'], 'C':[0.001,0.01,0.1,1,10,100],'gamma':[0.001,0.01,0.1,1,10,100]},
    {'kernel':['linear'], 'C':[0.001,0.01,0.1,1,10,100],'gamma':[0.001,0.01,0.1,1,10,100]}]

In [40]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(SVC(), param_grid, cv=5)

In [41]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [0.001, 0.01, 0.1, 1, 10, 100],
                          'gamma': [0.001, 0.01, 0.1, 1, 10, 100],
                          'kernel': ['rbf']},
                         {'C': [0.001, 0.01, 0.1, 1, 10, 100],
                          'gamma': [0.001, 0.01, 0.1, 1, 10, 100],
                          'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [42]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}
0.9707024557395775
0.9415204678362573


In [43]:
param_distribs = [{'kernel':['rbf'], 'C':randint(low=0.001, high=100),'gamma':randint(low=0.001, high=100)},
    {'kernel':['linear'], 'C':randint(low=0.001, high=100),'gamma':randint(low=0.001, high=100)}]

In [44]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(), param_distribs, cv=5, n_iter=100)
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                 class_weight=None, coef0=0.0,
                                 decision_function_shape='ovr', degree=3,
                                 gamma='scale', kernel='rbf', max_iter=-1,
                                 probability=False, random_state=None,
                                 shrinking=True, tol=0.001, verbose=False),
                   iid='deprecated', n_iter=100, n_jobs=None,
                   param_distributions=[{'C': <scipy.sta...
                                         'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fa68e8a15d0>,
                                         'kernel': ['rbf']},
                                        {'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fa6996e4950>,
                                         'gamma': <scipy.stats._distn_infrastructure.rv_frozen object 

In [45]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'C': 2, 'gamma': 33, 'kernel': 'linear'}
0.9648581762802209
0.9473684210526315


In [46]:
data = pd.read_csv('house_price.csv')
X = data[data.columns[0:4]]
y = data["house_value"]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
mms = MinMaxScaler()
mms.fit(X_train)
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [47]:
from sklearn.svm import SVR
model = SVR(kernel='poly')
model.fit(X_scaled_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [48]:
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

In [49]:
print(model.score(X_scaled_train, y_train))
print(model.score(X_scaled_test, y_test))

0.42753872325461695
0.4417483576515683


In [50]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [51]:
mse_train = mean_squared_error(y_train, pred_train)
mse_test = mean_squared_error(y_test, pred_test)

In [52]:
rmse_train = np.sqrt(mse_train)
rmse_test = np.sqrt(mse_test)

In [53]:
from sklearn.model_selection import GridSearchCV
param_grid = {'kernel':['poly'],'C':[0.01,0.1,1,10], 'gamma':[0.01,0.1,1,10]}
#'kernel':['poly'],
gs = GridSearchCV(SVR(kernel='poly'), param_grid, cv=5)


In [54]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='scale', kernel='poly',
                           max_iter=-1, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.01, 0.1, 1, 10], 'gamma': [0.01, 0.1, 1, 10],
                         'kernel': ['poly']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [55]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'C': 10, 'gamma': 10, 'kernel': 'poly'}
0.5341165008948594
0.5405171559274444


In [56]:
param_distribs = {'kernel':['poly'], 'C':randint(low=0.01, high=10), 'gamma':randint(low=0.01, high=10)}
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVR(kernel='poly'), param_distribs, n_iter=20, cv=5)
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                                 epsilon=0.1, gamma='scale', kernel='poly',
                                 max_iter=-1, shrinking=True, tol=0.001,
                                 verbose=False),
                   iid='deprecated', n_iter=20, n_jobs=None,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fa68e89f5d0>,
                                        'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fa68e89f0d0>,
                                        'kernel': ['poly']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [57]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'C': 7, 'gamma': 9, 'kernel': 'poly'}
0.5245305679125154
0.5360661620754696


#의사결정나무

In [58]:
import pandas as pd
data = pd.read_csv('breast-cancer-wisconsin.csv')
X = data[data.columns[1:10]]
y = data['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(X_train)
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [59]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)

In [60]:
print(model.score(X_scaled_train, y_train))

1.0


In [60]:
from sklearn.metrics import confusion_matrix
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)

In [61]:
from sklearn.metrics import classification_report
cr_train = classification_report(y_train, pred_train)
cr_test = classification_report(y_test, pred_test)

In [62]:
print(cm_train)
print(cm_test)
print(cr_train)
print(cr_test)

[[335   6]
 [  5 166]]
[[101   2]
 [  7  61]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       341
           1       0.97      0.97      0.97       171

    accuracy                           0.98       512
   macro avg       0.98      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512

              precision    recall  f1-score   support

           0       0.94      0.98      0.96       103
           1       0.97      0.90      0.93        68

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [68]:
param_grid = {'max_depth':range(2,20,2), 'min_samples_leaf':range(1,50,2)}

In [69]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5)
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': range(2, 20, 2),
                       

In [70]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_train, y_train))

{'max_depth': 4, 'min_samples_leaf': 1}
0.9629164287074052
0.974609375


In [73]:
from scipy.stats import randint
param_distribs = {'max_depth':randint(low=1,high=20), 'min_samples_leaf':randint(low=1,high=50)}

In [77]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(DecisionTreeClassifier(), param_distribs, cv=5)
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort='deprecated',
                                                    random_state=None,
          

In [78]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_train, y_train))

{'max_depth': 4, 'min_samples_leaf': 8}
0.9628973919664954
0.962890625


In [79]:
data = pd.read_csv('house_price.csv')
X = data[data.columns[0:4]]
y = data["house_value"]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
mms = MinMaxScaler()
mms.fit(X_train)
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [81]:
from sklearn.tree import DecisionTreeRegressor

In [82]:
dtr = DecisionTreeRegressor()
dtr.fit(X_scaled_train,y_train)
dtr.score(X_scaled_train,y_train)

1.0

In [89]:
pred_test = dtr.predict(X_scaled_test)
pred_train = dtr.predict(X_scaled_train)

In [86]:
dtr.score(X_scaled_test, y_test)

0.2693540747216093

In [90]:
import numpy as np
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_train , pred_train)
rmse = np.sqrt(mse)
print(rmse)

0.0


In [91]:
mse = mean_squared_error(y_test , pred_test)
rmse = np.sqrt(mse)
print(rmse)

81717.66661907919


In [92]:
param_grid = {'max_depth':range(2,20,2), 'min_samples_leaf':range(1,50,2)}

In [93]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(DecisionTreeRegressor(), param_grid, cv=5)
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse',
                                             max_depth=None, max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort='deprecated',
                                             random_state=None,
                                             splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': range(2, 20, 2),
                         'min_samples_leaf': range(1, 50, 2)},
             pre_dispatch='2*n_jobs',

In [94]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_train, y_train))

{'max_depth': 10, 'min_samples_leaf': 39}
0.588474171891088
0.6496049775818675


In [95]:
from scipy.stats import randint
param_distribs = {'max_depth':randint(low=1,high=20), 'min_samples_leaf':randint(low=1,high=50)}

In [96]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(DecisionTreeRegressor(), param_distribs, cv=5)
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=DecisionTreeRegressor(ccp_alpha=0.0,
                                                   criterion='mse',
                                                   max_depth=None,
                                                   max_features=None,
                                                   max_leaf_nodes=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   presort='deprecated',
                                                   random_state=None,
                                                   splitter='best'),
                   iid='d

In [97]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_train, y_train))

{'max_depth': 10, 'min_samples_leaf': 38}
0.5877378527852202
0.6506316092036522
