<a href="https://colab.research.google.com/github/holdenkim/codingT/blob/main/BBGS_Part4_123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 로지스틱 회귀

In [ ]:
import pandas as pd
data = pd.read_csv("breast-cancer-wisconsin.csv")

In [ ]:
data.head()

code  Clump_Thickness  Cell_Size  ...  Normal_Nucleoli  Mitoses  Class
0  1000025                5          1  ...                1        1      0
1  1002945                5          4  ...                2        1      0
2  1015425                3          1  ...                1        1      0
3  1016277                6          8  ...                7        1      0
4  1017023                4          1  ...                1        1      0

[5 rows x 11 columns]

In [ ]:
import warnings 
warnings.filterwarnings("ignore")

In [ ]:
X = data[data.columns[1:10]]
y= data[["Class"]]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,stratify=y, random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model.fit(X_scaled_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

In [ ]:
print(model.score(X_scaled_train, y_train))
print(model.score(X_scaled_test, y_test,))

0.97265625
0.9590643274853801


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)

In [ ]:
print(cm_train)
print(cm_test)

[[328   5]
 [  9 170]]
[[106   5]
 [  2  58]]


In [ ]:
from sklearn.metrics import classification_report
cr_train = classification_report(y_train, pred_train)
cr_test = classification_report(y_test, pred_test)

In [ ]:
print(cr_train)
print(cr_test)

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       333
           1       0.97      0.95      0.96       179

    accuracy                           0.97       512
   macro avg       0.97      0.97      0.97       512
weighted avg       0.97      0.97      0.97       512

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       111
           1       0.92      0.97      0.94        60

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params_grid = {'C':[0.001,0.01,0.1,1,10,100]}

In [ ]:
gs = GridSearchCV(LogisticRegression(), params_grid, cv=5)

In [ ]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'C': 10}
0.972606129830573
0.9590643274853801


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [ ]:
param_rand = {'C': randint(low=0.001, high=100)}

In [ ]:
rs = RandomizedSearchCV(LogisticRegression(),  param_rand, cv=5)

In [ ]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f60f6f44a10>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [ ]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'C': 20}
0.972606129830573
0.9590643274853801


#K 최근접 이웃법

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model = KNeighborsClassifier()
model.fit(X_scaled_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

In [ ]:
print(model.score(X_scaled_train, y_train))
print(model.score(X_scaled_test, y_test))

0.984375
0.9532163742690059


In [ ]:
cm_neighbors_train = confusion_matrix(y_train, pred_train)
cm_neighbors_test = confusion_matrix(y_test, pred_test)

In [ ]:
print(cm_neighbors_train)
print(cm_neighbors_test)

[[331   2]
 [  6 173]]
[[106   5]
 [  3  57]]


In [ ]:
cr_neighbors_train = classification_report(y_train, pred_train)
cr_neighbors_test = classification_report(y_test, pred_test)

In [ ]:
print(cr_neighbors_train)
print(cr_neighbors_test)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       333
           1       0.99      0.97      0.98       179

    accuracy                           0.98       512
   macro avg       0.99      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512

              precision    recall  f1-score   support

           0       0.97      0.95      0.96       111
           1       0.92      0.95      0.93        60

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [ ]:
param_neighbors = {'n_neighbors':[1,3,5,7,9,11]}

In [ ]:
gs_neighbors = GridSearchCV(KNeighborsClassifier(), param_neighbors, cv=5)

In [ ]:
gs_neighbors.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
print(gs_neighbors.best_params_)
print(gs_neighbors.best_score_)
print(gs_neighbors.score(X_scaled_test, y_test))

{'n_neighbors': 3}
0.9823910146582906
0.9532163742690059


In [ ]:
param_neighbors_rand = {'n_neighbors':randint(low=1, high=11)}

In [ ]:
rs_neighbors = RandomizedSearchCV(KNeighborsClassifier(), param_neighbors_rand, cv=5)

In [ ]:
rs_neighbors.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=KNeighborsClassifier(algorithm='auto',
                                                  leaf_size=30,
                                                  metric='minkowski',
                                                  metric_params=None,
                                                  n_jobs=None, n_neighbors=5,
                                                  p=2, weights='uniform'),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'n_neighbors': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f60f64f0490>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [ ]:
print(rs_neighbors.best_params_)
print(rs_neighbors.best_score_)
print(rs_neighbors.score(X_scaled_test, y_test))

{'n_neighbors': 3}
0.9823910146582906
0.9532163742690059


In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
data = pd.read_csv('house_price.csv')

In [ ]:
data.head()

housing_age  income  bedrooms  households     rooms  house_value
0           23  6.7770  0.141112    2.442244  8.103960       500000
1           49  6.0199  0.160984    2.726688  5.752412       500000
2           35  5.1155  0.249061    1.902676  3.888078       500000
3           32  4.7109  0.231383    1.913669  4.508393       500000
4           21  4.5625  0.255583    3.092664  4.667954       500000

In [ ]:
X = data[data.columns[0:4]]
y = data["house_value"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [ ]:
mms = MinMaxScaler()

In [ ]:
mms.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [ ]:
knr = KNeighborsRegressor()

In [ ]:
knr.fit(X_scaled_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [131]:
pred_train = knr.predict(X_scaled_train)
pred_test = knr.predict(X_scaled_test)

In [132]:
print(knr.score(X_scaled_train, y_train))
print(knr.score(X_scaled_test, y_test))

0.7117228242101499
0.5824837770609437


In [133]:
#RMSE

In [134]:
import numpy as np

In [135]:
from sklearn.metrics import mean_squared_error

In [138]:
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)

In [139]:
print(np.sqrt(MSE_train))
print(np.sqrt(MSE_test))

51245.551730177634
61773.065157626545


In [160]:
param_grid = {'n_neighbors':[1,3,5,7,9,11, 13, 15, 17, 19, 21]}

In [161]:
gs = GridSearchCV(KNeighborsRegressor(),param_grid, cv=5 )

In [162]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                           metric='minkowski',
                                           metric_params=None, n_jobs=None,
                                           n_neighbors=5, p=2,
                                           weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19,
                                         21]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [163]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'n_neighbors': 19}
0.617495448414482
0.6273543979017522


In [164]:
param_rand = {'n_neighbors':randint(low=1, high=20)}

In [169]:
rs = RandomizedSearchCV(KNeighborsRegressor(), param_distributions = param_rand, cv=5, n_iter=20)

In [170]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                                 metric='minkowski',
                                                 metric_params=None,
                                                 n_jobs=None, n_neighbors=5,
                                                 p=2, weights='uniform'),
                   iid='deprecated', n_iter=20, n_jobs=None,
                   param_distributions={'n_neighbors': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f60f6036ed0>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [171]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'n_neighbors': 19}
0.617495448414482
0.6273543979017522


In [172]:
# 데이터 양이 많을때는 k값을 늘려서 가까운 주변의 여러 데이터의 평균으로 예측 하는것이 성능과 일반화 모두에 도움이 된다

#나이브베이즈

In [173]:
#ㅇㄻㄴ