<a href="https://colab.research.google.com/github/holdenkim/codingT/blob/main/BBGS_Part4_123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 로지스틱 회귀

In [ ]:
import pandas as pd
data = pd.read_csv("breast-cancer-wisconsin.csv")

In [ ]:
data.head()

code  Clump_Thickness  Cell_Size  ...  Normal_Nucleoli  Mitoses  Class
0  1000025                5          1  ...                1        1      0
1  1002945                5          4  ...                2        1      0
2  1015425                3          1  ...                1        1      0
3  1016277                6          8  ...                7        1      0
4  1017023                4          1  ...                1        1      0

[5 rows x 11 columns]

In [ ]:
import warnings 
warnings.filterwarnings("ignore")

In [ ]:
X = data[data.columns[1:10]]
y= data[["Class"]]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,stratify=y, random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model.fit(X_scaled_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

In [ ]:
print(model.score(X_scaled_train, y_train))
print(model.score(X_scaled_test, y_test,))

0.97265625
0.9590643274853801


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)

In [ ]:
print(cm_train)
print(cm_test)

[[328   5]
 [  9 170]]
[[106   5]
 [  2  58]]


In [ ]:
from sklearn.metrics import classification_report
cr_train = classification_report(y_train, pred_train)
cr_test = classification_report(y_test, pred_test)

In [ ]:
print(cr_train)
print(cr_test)

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       333
           1       0.97      0.95      0.96       179

    accuracy                           0.97       512
   macro avg       0.97      0.97      0.97       512
weighted avg       0.97      0.97      0.97       512

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       111
           1       0.92      0.97      0.94        60

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params_grid = {'C':[0.001,0.01,0.1,1,10,100]}

In [ ]:
gs = GridSearchCV(LogisticRegression(), params_grid, cv=5)

In [ ]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'C': 10}
0.972606129830573
0.9590643274853801


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [ ]:
param_rand = {'C': randint(low=0.001, high=100)}

In [ ]:
rs = RandomizedSearchCV(LogisticRegression(),  param_rand, cv=5)

In [ ]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f60f6f44a10>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [ ]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'C': 20}
0.972606129830573
0.9590643274853801


#K 최근접 이웃법

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model = KNeighborsClassifier()
model.fit(X_scaled_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)

In [ ]:
print(model.score(X_scaled_train, y_train))
print(model.score(X_scaled_test, y_test))

0.984375
0.9532163742690059


In [ ]:
cm_neighbors_train = confusion_matrix(y_train, pred_train)
cm_neighbors_test = confusion_matrix(y_test, pred_test)

In [ ]:
print(cm_neighbors_train)
print(cm_neighbors_test)

[[331   2]
 [  6 173]]
[[106   5]
 [  3  57]]


In [ ]:
cr_neighbors_train = classification_report(y_train, pred_train)
cr_neighbors_test = classification_report(y_test, pred_test)

In [ ]:
print(cr_neighbors_train)
print(cr_neighbors_test)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       333
           1       0.99      0.97      0.98       179

    accuracy                           0.98       512
   macro avg       0.99      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512

              precision    recall  f1-score   support

           0       0.97      0.95      0.96       111
           1       0.92      0.95      0.93        60

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [ ]:
param_neighbors = {'n_neighbors':[1,3,5,7,9,11]}

In [ ]:
gs_neighbors = GridSearchCV(KNeighborsClassifier(), param_neighbors, cv=5)

In [ ]:
gs_neighbors.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
print(gs_neighbors.best_params_)
print(gs_neighbors.best_score_)
print(gs_neighbors.score(X_scaled_test, y_test))

{'n_neighbors': 3}
0.9823910146582906
0.9532163742690059


In [ ]:
param_neighbors_rand = {'n_neighbors':randint(low=1, high=11)}

In [ ]:
rs_neighbors = RandomizedSearchCV(KNeighborsClassifier(), param_neighbors_rand, cv=5)

In [ ]:
rs_neighbors.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=KNeighborsClassifier(algorithm='auto',
                                                  leaf_size=30,
                                                  metric='minkowski',
                                                  metric_params=None,
                                                  n_jobs=None, n_neighbors=5,
                                                  p=2, weights='uniform'),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'n_neighbors': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f60f64f0490>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [ ]:
print(rs_neighbors.best_params_)
print(rs_neighbors.best_score_)
print(rs_neighbors.score(X_scaled_test, y_test))

{'n_neighbors': 3}
0.9823910146582906
0.9532163742690059


In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
data = pd.read_csv('house_price.csv')

In [ ]:
data.head()

housing_age  income  bedrooms  households     rooms  house_value
0           23  6.7770  0.141112    2.442244  8.103960       500000
1           49  6.0199  0.160984    2.726688  5.752412       500000
2           35  5.1155  0.249061    1.902676  3.888078       500000
3           32  4.7109  0.231383    1.913669  4.508393       500000
4           21  4.5625  0.255583    3.092664  4.667954       500000

In [ ]:
X = data[data.columns[0:4]]
y = data["house_value"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [ ]:
mms = MinMaxScaler()

In [ ]:
mms.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
X_scaled_train = mms.transform(X_train)
X_scaled_test = mms.transform(X_test)

In [ ]:
knr = KNeighborsRegressor()

In [ ]:
knr.fit(X_scaled_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [ ]:
pred_train = knr.predict(X_scaled_train)
pred_test = knr.predict(X_scaled_test)

In [ ]:
print(knr.score(X_scaled_train, y_train))
print(knr.score(X_scaled_test, y_test))

0.7117228242101499
0.5824837770609437


In [ ]:
#RMSE

In [ ]:
import numpy as np

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)

In [ ]:
print(np.sqrt(MSE_train))
print(np.sqrt(MSE_test))

51245.551730177634
61773.065157626545


In [ ]:
param_grid = {'n_neighbors':[1,3,5,7,9,11, 13, 15, 17, 19, 21]}

In [ ]:
gs = GridSearchCV(KNeighborsRegressor(),param_grid, cv=5 )

In [ ]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                           metric='minkowski',
                                           metric_params=None, n_jobs=None,
                                           n_neighbors=5, p=2,
                                           weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19,
                                         21]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'n_neighbors': 19}
0.617495448414482
0.6273543979017522


In [ ]:
param_rand = {'n_neighbors':randint(low=1, high=20)}

In [ ]:
rs = RandomizedSearchCV(KNeighborsRegressor(), param_distributions = param_rand, cv=5, n_iter=20)

In [ ]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                                 metric='minkowski',
                                                 metric_params=None,
                                                 n_jobs=None, n_neighbors=5,
                                                 p=2, weights='uniform'),
                   iid='deprecated', n_iter=20, n_jobs=None,
                   param_distributions={'n_neighbors': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f60f6036ed0>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [ ]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'n_neighbors': 19}
0.617495448414482
0.6273543979017522


In [ ]:
# 데이터 양이 많을때는 k값을 늘려서 가까운 주변의 여러 데이터의 평균으로 예측 하는것이 성능과 일반화 모두에 도움이 된다

#나이브베이즈

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("breast-cancer-wisconsin.csv")

In [3]:
data.head(1)

code  Clump_Thickness  Cell_Size  ...  Normal_Nucleoli  Mitoses  Class
0  1000025                5          1  ...                1        1      0

[1 rows x 11 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [5]:
X = data[data.columns[1:10]]
y = data['Class']

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [49]:
from sklearn.preprocessing import StandardScaler

In [8]:
ss = StandardScaler()

In [9]:
ss.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
X_scaled_train = ss.transform(X_train)
X_scaled_test = ss.transform(X_test)

In [11]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)
print(model.score(X_scaled_train, y_train))

0.958984375


In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
mm = MinMaxScaler()
mm.fit(X_train)
X_scaled_train = mm.transform(X_train)
X_scaled_test = mm.transform(X_test)

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)
pred_test = model.predict(X_scaled_test)
print(model.score(X_scaled_train, y_train))

0.958984375


In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
cm_train = confusion_matrix(y_train, pred_train)
cm_test = confusion_matrix(y_test, pred_test)

In [17]:
print(cm_train)
print(cm_test)

[[324  17]
 [  4 167]]
[[100   3]
 [  3  65]]


In [18]:
from sklearn.metrics import classification_report

In [19]:
cr_train = classification_report(y_train, pred_train)
cr_test = classification_report(y_test, pred_test)

In [20]:
print(cr_train)
print(cr_test)

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       341
           1       0.91      0.98      0.94       171

    accuracy                           0.96       512
   macro avg       0.95      0.96      0.95       512
weighted avg       0.96      0.96      0.96       512

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       103
           1       0.96      0.96      0.96        68

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
param_grid1 = {"var_smoothing":[0,1,2,3,4,5,6,7,8,9,10]}

In [23]:
gs = GridSearchCV(GaussianNB(), param_grid1, cv=5)

In [24]:
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=GaussianNB(priors=None, var_smoothing=1e-09),
             iid='deprecated', n_jobs=None,
             param_grid={'var_smoothing': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [25]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'var_smoothing': 1}
0.9590138968208644
0.9064327485380117


In [26]:
from scipy.stats import randint

In [27]:
param_distribs = {"var_smoothing":randint(low=0, high=20)}

In [28]:
from sklearn.model_selection import RandomizedSearchCV

In [29]:
rs = RandomizedSearchCV(GaussianNB(), param_distribs, n_iter=100, cv=5)

In [30]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                   iid='deprecated', n_iter=100, n_jobs=None,
                   param_distributions={'var_smoothing': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f1cfaca4990>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [31]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'var_smoothing': 1}
0.9590138968208644
0.9064327485380117


In [32]:
#나이브베이즈 성능은 그리 좋지 않다. 로지스틱보다 보통 안 좋다

In [59]:
data = pd.read_csv('house_price.csv')

In [60]:
data.head(1)

housing_age  income  bedrooms  households    rooms  house_value
0           23   6.777  0.141112    2.442244  8.10396       500000

In [61]:
X = data[data.columns[0:5]]
y = data['house_value']

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [63]:
mm = MinMaxScaler()
mm.fit(X_train)
X_scaled_train = mm.transform(X_train)
X_scaled_test = mm.transform(X_test)

In [64]:
from sklearn.linear_model import BayesianRidge

In [65]:
model =BayesianRidge()

In [66]:
model.fit(X_scaled_train, y_train)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, alpha_init=None,
              compute_score=False, copy_X=True, fit_intercept=True,
              lambda_1=1e-06, lambda_2=1e-06, lambda_init=None, n_iter=300,
              normalize=False, tol=0.001, verbose=False)

In [67]:
pred_train = model.predict(X_scaled_train)

In [68]:
print(model.score(X_scaled_train, y_train))

0.5706920449333218


In [69]:
pred_test = model.predict(X_scaled_test)

In [70]:
model.score(X_scaled_test, y_test)

0.5826111218474419

In [71]:
import numpy as np

In [73]:
from sklearn.metrics import mean_squared_error

In [80]:
mse_train = mean_squared_error (y_train, pred_train)
mse_test = mean_squared_error (y_test, pred_test)

In [81]:
rmse_train = np.sqrt(mse_train)
rmse_test = np.sqrt(mse_test)

In [83]:
print(rmse_train)

62536.779446730005


In [84]:
print(rmse_test)

61763.64387375415


In [86]:
from sklearn.model_selection import GridSearchCV


In [87]:
param_grid = {"alpha_1":[1e-06, 1e-05, 1e04, 1e-03, 1e-02, 1e-01, 1,2,3,4],
              "lambda_1":[1e-06, 1e-05, 1e04, 1e-03, 1e-02, 1e-01, 1,2,3,4]
}

In [89]:
gs = GridSearchCV ( BayesianRidge(), param_grid, cv=5)
gs.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=BayesianRidge(alpha_1=1e-06, alpha_2=1e-06,
                                     alpha_init=None, compute_score=False,
                                     copy_X=True, fit_intercept=True,
                                     lambda_1=1e-06, lambda_2=1e-06,
                                     lambda_init=None, n_iter=300,
                                     normalize=False, tol=0.001,
                                     verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha_1': [1e-06, 1e-05, 10000.0, 0.001, 0.01, 0.1, 1,
                                     2, 3, 4],
                         'lambda_1': [1e-06, 1e-05, 10000.0, 0.001, 0.01, 0.1,
                                      1, 2, 3, 4]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [90]:
print(gs.best_params_)
print(gs.best_score_)
print(gs.score(X_scaled_test, y_test))

{'alpha_1': 4, 'lambda_1': 1e-06}
0.5702758458286125
0.5826111202240445


In [91]:
from scipy.stats import randint

In [92]:
param_distribs = {
    "alpha_1":randint(low=1e-06, high=10),
    "lambda_1": randint(low=1e-06, high=10)

}

In [93]:
from sklearn.model_selection import RandomizedSearchCV

In [94]:
rs =  RandomizedSearchCV(BayesianRidge(), param_distribs, cv=5)

In [95]:
rs.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=BayesianRidge(alpha_1=1e-06, alpha_2=1e-06,
                                           alpha_init=None, compute_score=False,
                                           copy_X=True, fit_intercept=True,
                                           lambda_1=1e-06, lambda_2=1e-06,
                                           lambda_init=None, n_iter=300,
                                           normalize=False, tol=0.001,
                                           verbose=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'alpha_1': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f1cef43c8d0>,
                                        'lambda_1': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f1cef43c850>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose

In [96]:
print(rs.best_params_)
print(rs.best_score_)
print(rs.score(X_scaled_test, y_test))

{'alpha_1': 5, 'lambda_1': 0}
0.5702758458379559
0.5826111198174153
