<a href="https://colab.research.google.com/github/holdenkim/codingT/blob/main/Kosta_Data_Analy_Lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [1]:
print("Hello World")

Hello World


In [4]:
"""
주석처리가 된다
"""
print("hello")

hello


In [14]:
i = int(30)
f= float(32.333)
b = bool(1)
n= None

print(i)
print(f)
print(b)
print(n)

30
32.333
True
None


In [143]:
#num1 = int(input("첫번째 숫자 넣어주세요:  "))
#print(num1)

첫번째 숫자 넣어주세요:  22


In [15]:
j = int(15)

In [22]:
r = 2**4
print (r)

16


In [35]:
s = "string is the best method"
t = "to do the final fantasy!"

In [36]:
r = s+t
print(r)

string is the best methodto do the final fantasy!


In [39]:
r[2:30:2]

'rn stebs ehdod'

In [44]:
t= (1,2,3)
print(t)

(1, 2, 3)


In [45]:
l=[1,2,3]
print(l)

[1, 2, 3]


In [48]:
l[0]=4

In [51]:
l.append(12)

In [56]:
l

[2, 3, 12]

In [55]:
l.remove(4)

In [57]:
a= ['하나','둘','셋','넷']

In [62]:
a.remove("셋")

In [65]:
print(a.index('하나'))

0


In [77]:
b =[1,12,5,8,9]

In [81]:
b.sort(reverse=True)

In [82]:
print(b)

[12, 9, 8, 5, 1]


In [83]:
a = (0)
b = (0,)
c = 1,2,3

In [84]:
print(a)
print(b)
print(c)

0
(0,)
(1, 2, 3)


In [85]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'tuple'>
<class 'tuple'>


In [86]:
dic1 = {"a":"1", "b":"2"}

In [88]:
dic1["a"]

'1'

In [97]:
a = -1

if a>3:
  print("A가 3보다 커요")
elif a>0:
  print("A가 양수예요")
else:
  print("A가 음수네요")

A가 음수네요


In [99]:
list1 = [1,2,3,4]

for i in (list1):
  print(i)

1
2
3
4


In [146]:
a =[["apple", "banna", "cherry"],1,2,3]

In [152]:
a[0][1][0]

'b'

In [105]:
for i in range(12):
  print("프린트",i)

프린트 0
프린트 1
프린트 2
프린트 3
프린트 4
프린트 5
프린트 6
프린트 7
프린트 8
프린트 9
프린트 10
프린트 11


In [106]:
a = "Kaggle"

for x in a:
    print(x)

    if x == 'g':
        break

K
a
g


In [107]:
alphabets = ['A', 'B', 'C']
for index, value in enumerate(alphabets):
    print(index, value)

0 A
1 B
2 C


In [108]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = list1+list2

In [109]:
print(list3)

[1, 2, 3, 4, 5, 6]


In [110]:
import numpy as np

In [111]:
a = [1,2,3]
b = [4,5,6]
c= np.array(a)+np.array(b)

In [112]:
print(c)

[5 7 9]


In [131]:
new_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [132]:
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [116]:
"""
리스트 []
튜플 (,)
딕셔너리{"":"", "":", "":""}
"""

'\n리스트 []\n튜플 (,)\n딕셔너리{"":"", "":", "":""}\n'

In [133]:
new = new_array.reshape(2,-1)

In [134]:
new

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [140]:
new.reshape(8,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])