<a href="https://colab.research.google.com/github/holdenkim/codingT/blob/main/Kosta_Data_Analy_Lib_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###기본

In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
"""
주석처리가 된다
"""
print("hello")

hello


###변수 리스트 튜플 딕셔너리

In [4]:
i = int(30)
f= float(32.333)
b = bool(1)
n= None

print(i)
print(f)
print(b)
print(n)

30
32.333
True
None


In [5]:
#num1 = int(input("첫번째 숫자 넣어주세요:  "))
#print(num1)

In [6]:
j = int(15)

In [7]:
r = 2**4
print (r)

16


In [8]:
s = "string is the best method"
t = "to do the final fantasy!"

In [9]:
r = s+t
print(r)

string is the best methodto do the final fantasy!


In [10]:
r[2:30:2]

'rn stebs ehdod'

In [11]:
t= (1,2,3)
print(t)

(1, 2, 3)


In [12]:
l=[1,2,3]
print(l)

[1, 2, 3]


In [13]:
l[0]=4

In [14]:
l.append(12)

In [15]:
l

[4, 2, 3, 12]

In [16]:
l.remove(4)

In [17]:
a= ['하나','둘','셋','넷']

In [18]:
a.remove("셋")

In [19]:
print(a.index('하나'))

0


In [20]:
b =[1,12,5,8,9]

In [21]:
b.sort(reverse=True)

In [22]:
list1 = [1,2,3,4,5]

In [23]:
list1.append(6)

In [24]:
list1

[1, 2, 3, 4, 5, 6]

In [25]:
list1.remove(2)

In [26]:
list1

[1, 3, 4, 5, 6]

In [27]:
list1.pop(1)

3

In [28]:
list1

[1, 4, 5, 6]

In [29]:
print(b)

[12, 9, 8, 5, 1]


In [30]:
a = (0)
b = (0,)
c = 1,2,3

In [31]:
print(a)
print(b)
print(c)

0
(0,)
(1, 2, 3)


In [32]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'tuple'>
<class 'tuple'>


In [33]:
dic1 = {"a":"1", "b":"2"}

In [34]:
dic1["a"]

'1'

In [35]:
print(dic1)

{'a': '1', 'b': '2'}


### if for 문

In [36]:
a = -1

if a>3:
  print("A가 3보다 커요")
elif a>0:
  print("A가 양수예요")
else:
  print("A가 음수네요")

A가 음수네요


In [37]:
list1 = [1,2,3,4]

for i in (list1):
  print(i)

1
2
3
4


In [38]:
a =[["apple", "banna", "cherry"],1,2,3]

In [39]:
a[0][1][-5]

'b'

In [40]:
for i in range(12):
  print("프린트",i)

프린트 0
프린트 1
프린트 2
프린트 3
프린트 4
프린트 5
프린트 6
프린트 7
프린트 8
프린트 9
프린트 10
프린트 11


In [41]:
a = "Kaggle"

for x in a:
    print(x)

    if x == 'g':
        break

K
a
g


In [42]:
alphabets = ['A', 'B', 'C']
for index, value in enumerate(alphabets):
    print(index, value)

0 A
1 B
2 C


In [43]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = list1+list2

In [44]:
print(list3)

[1, 2, 3, 4, 5, 6]


### 넘파이

In [45]:
import numpy as np

In [46]:
a = [1,2,3]
b = [4,5,6]
c= np.array(a)+np.array(b)

In [47]:
print(c)

[5 7 9]


In [48]:
"""
리스트 []
튜플 (,)
딕셔너리{"":"", "":", "":""}
"""

'\n리스트 []\n튜플 (,)\n딕셔너리{"":"", "":", "":""}\n'

In [49]:
myarray = np.array([[[1,2],[1,2]],[[3,4],[5,6]]])

In [50]:
myarray.shape
myarray.dtype

dtype('int64')

In [51]:
my_arra_1 = np.array([1,2])

In [52]:
my_arra_1.shape

(2,)

In [53]:
new_arr = np.arange(4)
new_arr2 = np.arange(1,11,2)
new_arr3 = np.zeros((3,2))
ones_array = np.ones((3,4), dtype='int32')

In [55]:
new_arr2
new_arr3
print(type(new_arr[1]))

<class 'numpy.int64'>


In [56]:
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [57]:
after_reshape = ones_array.reshape(6,-1)
after_reshape1 = ones_array.reshape(6,2)

In [58]:
after_reshape

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [59]:
after_reshape1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [60]:
new_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [61]:
new_array = np.arange(1,17)

In [62]:
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [63]:
new = new_array.reshape(2,-1)

In [64]:
new

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [65]:
new.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [66]:
new.shape

(2, 8)

In [67]:
a = np.array([0,1,2])
b = np.array([[0,1,2],[10,11,12],[21,22,23]])

In [68]:
b

array([[ 0,  1,  2],
       [10, 11, 12],
       [21, 22, 23]])

In [69]:
a+b

array([[ 0,  2,  4],
       [10, 12, 14],
       [21, 23, 25]])

In [70]:
a

array([0, 1, 2])

In [71]:
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [72]:
ones_array.reshape(-1,2)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

###판다스

In [73]:
import pandas as pd
print(pd.__version__)

1.1.5


##기본

In [87]:
df1 = pd.DataFrame(
#    {'col1':[1,2,3], "col2":[4,5,6]}
    {'name':['John','John1','John2'],
     'age':[22,33,44],
      'job':["asd","ddd",'job']
    }  
    
    )
df1

name  age  job
0   John   22  asd
1  John1   33  ddd
2  John2   44  job

In [75]:
df2 = pd.DataFrame([
                  {'name':'Jonh', 'age':25, 'job':'asb'},
                  {'name':'Jonh1', 'age':34, 'job':'job'},
                  {'name':'Jonh2','age':44, 'job':'stud'}
])
#딕셔너리사용했음

In [76]:
df2

name  age   job
0   Jonh   25   asb
1  Jonh1   34   job
2  Jonh2   44  stud

In [77]:
from collections import OrderedDict

friend_ordered_dict= OrderedDict(
        [
         
         ('name',['John','Jenny','Nate','Alice',"Bob","Chuck","Daniel"]),
              ('age',[20,30,30,25,25,24,40]),
              ('job',["students",'developer',"taecher","students",'developer',"taecher","taecher"])
              ] 
)
df3 =pd.DataFrame(friend_ordered_dict)
#오더드딕 사용했음

In [78]:
df3

name  age        job
0    John   20   students
1   Jenny   30  developer
2    Nate   30    taecher
3   Alice   25   students
4     Bob   25  developer
5   Chuck   24    taecher
6  Daniel   40    taecher

##10분 연습


In [99]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [94]:
dates = pd.date_range("20210923", periods=6)
dates

DatetimeIndex(['2021-09-23', '2021-09-24', '2021-09-25', '2021-09-26',
               '2021-09-27', '2021-09-28'],
              dtype='datetime64[ns]', freq='D')

In [98]:
df = pd.DataFrame(np.random.randn(6,4), index=dates,columns=list("ABCD"))
df

A         B         C         D
2021-09-23  0.005041  1.777862  2.089980 -0.736021
2021-09-24  0.785561  0.498789  0.113831  0.520470
2021-09-25 -0.883052 -0.201887 -0.798046  0.555539
2021-09-26  0.409528 -1.297433 -0.340905 -0.308332
2021-09-27  0.319479  0.365681 -0.834390 -1.007302
2021-09-28 -0.640171 -0.405872  0.908877  0.461855

In [103]:
df2= pd.DataFrame(
  {
    "A":1.0,
    "B": pd.Timestamp('20210923'),
    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
    "D": np.array([3]*4, dtype="int32"),
    "E": pd.Categorical(["test","train","test","train"]),
    "F": "foo",  
  }
)
df2

A          B    C  D      E    F
0  1.0 2021-09-23  1.0  3   test  foo
1  1.0 2021-09-23  1.0  3  train  foo
2  1.0 2021-09-23  1.0  3   test  foo
3  1.0 2021-09-23  1.0  3  train  foo

##드라이브연결 데이터로드

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [89]:
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/kosta/PART_I_Intro/'
lemonade = pd.read_csv(DATA_PATH + 'data/Lemonade2016.csv')
lemonade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB


In [104]:
lemonade.head(10)

Date Location  Lemon  Orange  Temperature  Leaflets  Price
0  7/1/2016     Park     97      67           70      90.0   0.25
1  7/2/2016     Park     98      67           72      90.0   0.25
2  7/3/2016     Park    110      77           71     104.0   0.25
3  7/4/2016    Beach    134      99           76      98.0   0.25
4  7/5/2016    Beach    159     118           78     135.0   0.25
5  7/6/2016    Beach    103      69           82      90.0   0.25
6  7/6/2016    Beach    103      69           82      90.0   0.25
7  7/7/2016    Beach    143     101           81     135.0   0.25
8       NaN    Beach    123      86           82     113.0   0.25
9  7/9/2016    Beach    134      95           80     126.0   0.25

In [105]:
lemonade.describe()

Lemon      Orange  Temperature    Leaflets      Price
count   32.000000   32.000000    32.000000   31.000000  32.000000
mean   116.156250   80.000000    78.968750  108.548387   0.354687
std     25.823357   21.863211     4.067847   20.117718   0.113137
min     71.000000   42.000000    70.000000   68.000000   0.250000
25%     98.000000   66.750000    77.000000   90.000000   0.250000
50%    113.500000   76.500000    80.500000  108.000000   0.350000
75%    131.750000   95.000000    82.000000  124.000000   0.500000
max    176.000000  129.000000    84.000000  158.000000   0.500000

In [107]:
lemonade["Location"].value_counts()

Beach    17
Park     15
Name: Location, dtype: int64

In [108]:
lemonade["Sold"] = lemonade["Lemon"]+lemonade["Orange"]

In [109]:
lemonade.head()

Date Location  Lemon  Orange  Temperature  Leaflets  Price  Sold
0  7/1/2016     Park     97      67           70      90.0   0.25   164
1  7/2/2016     Park     98      67           72      90.0   0.25   165
2  7/3/2016     Park    110      77           71     104.0   0.25   187
3  7/4/2016    Beach    134      99           76      98.0   0.25   233
4  7/5/2016    Beach    159     118           78     135.0   0.25   277

In [110]:
lemonade["Revenue"] = lemonade["Price"]+lemonade["Sold"]

In [111]:
lemonade.head()

Date Location  Lemon  Orange  ...  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97      67  ...      90.0   0.25   164   164.25
1  7/2/2016     Park     98      67  ...      90.0   0.25   165   165.25
2  7/3/2016     Park    110      77  ...     104.0   0.25   187   187.25
3  7/4/2016    Beach    134      99  ...      98.0   0.25   233   233.25
4  7/5/2016    Beach    159     118  ...     135.0   0.25   277   277.25

[5 rows x 9 columns]

In [113]:
lemonade_column_drop = lemonade.drop("Sold", axis=1)

In [115]:
lemonade_column_drop.head(3)

Date Location  Lemon  Orange  Temperature  Leaflets  Price  Revenue
0  7/1/2016     Park     97      67           70      90.0   0.25   164.25
1  7/2/2016     Park     98      67           72      90.0   0.25   165.25
2  7/3/2016     Park    110      77           71     104.0   0.25   187.25

In [117]:
lemonade_row_drop = lemonade.drop(0, axis=0)

In [118]:
lemonade_row_drop.head(3)

Date Location  Lemon  Orange  ...  Leaflets  Price  Sold  Revenue
1  7/2/2016     Park     98      67  ...      90.0   0.25   165   165.25
2  7/3/2016     Park    110      77  ...     104.0   0.25   187   187.25
3  7/4/2016    Beach    134      99  ...      98.0   0.25   233   233.25

[3 rows x 9 columns]

In [119]:
print(lemonade[0:5])

       Date Location  Lemon  Orange  ...  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97      67  ...      90.0   0.25   164   164.25
1  7/2/2016     Park     98      67  ...      90.0   0.25   165   165.25
2  7/3/2016     Park    110      77  ...     104.0   0.25   187   187.25
3  7/4/2016    Beach    134      99  ...      98.0   0.25   233   233.25
4  7/5/2016    Beach    159     118  ...     135.0   0.25   277   277.25

[5 rows x 9 columns]


In [122]:
lemonade['Location']== "Beach"

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
Name: Location, dtype: bool

In [123]:
print(lemonade [lemonade['Location']!= "Beach"].head(3))

       Date Location  Lemon  Orange  ...  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97      67  ...      90.0   0.25   164   164.25
1  7/2/2016     Park     98      67  ...      90.0   0.25   165   165.25
2  7/3/2016     Park    110      77  ...     104.0   0.25   187   187.25

[3 rows x 9 columns]


In [125]:
print(lemonade.iloc[0:3,0:2])

       Date Location
0  7/1/2016     Park
1  7/2/2016     Park
2  7/3/2016     Park


In [126]:
print(lemonade.loc[0:2,["Date","Location","Revenue"]])

       Date Location  Revenue
0  7/1/2016     Park   164.25
1  7/2/2016     Park   165.25
2  7/3/2016     Park   187.25


In [128]:
print(lemonade.loc[lemonade['Revenue']>180, ["Date","Revenue"]    ])

         Date  Revenue
2    7/3/2016   187.25
3    7/4/2016   233.25
4    7/5/2016   277.25
7    7/7/2016   244.25
8         NaN   209.25
9    7/9/2016   229.25
10  7/10/2016   238.25
11  7/11/2016   282.25
12  7/12/2016   225.25
13  7/13/2016   184.25
14  7/14/2016   207.25
17  7/17/2016   191.50
18  7/18/2016   223.50
19  7/19/2016   207.50
22  7/22/2016   187.50
23  7/23/2016   202.50
24  7/24/2016   203.50
25  7/25/2016   269.50
26  7/26/2016   305.35
